name: Org Release
on:
    pull_request:
        types:
        - closed
        branches:
        - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-release.yml@72d0360b99f80252dda40f6dfefc252f5a66edb3 # v0.10.0